# Generated by Django 5.1.4 on 2026-01-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedyOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('source', models.CharField(default='boericke', max_length=20)),
                ('description', models.TextField(help_text='Short daily insight or keynotes about this remedy.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='remedies/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Remedies of the Day',
                'ordering': ['-created_at'],
            },
        ),
    ]
