# Generated by Django 5.1.4 on 2026-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remedyoftheday'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy', models.CharField(help_text='Name of the primary remedy', max_length=200, unique=True)),
                ('complements', models.TextField(blank=True, help_text='Remedies that act as complements')),
                ('follows', models.TextField(blank=True, help_text='Remedies that operate well after this')),
                ('antidotes', models.TextField(blank=True, help_text='Remedies that antidote this one')),
                ('inimical', models.TextField(blank=True, help_text='Incompatible remedies')),
                ('duration', models.CharField(blank=True, help_text='Duration of action', max_length=100)),
            ],
            options={
                'verbose_name': 'Remedy Relationship',
                'verbose_name_plural': 'Relationship Table (Gibson Miller)',
                'ordering': ['remedy'],
            },
        ),
    ]
