# Generated by Django 5.1.4 on 2026-01-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remedyrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedyrelationship',
            name='duration',
        ),
    ]
