# Generated by Django 5.1.4 on 2026-01-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_duration_from_remedy_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedyDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy', models.CharField(help_text='Name of the remedy', max_length=200, unique=True)),
                ('duration', models.CharField(help_text="Duration of action (e.g., '30-40 days')", max_length=100)),
            ],
            options={
                'verbose_name': 'Remedy Duration',
                'verbose_name_plural': 'Remedy Durations',
                'ordering': ['remedy'],
            },
        ),
    ]
