# Generated by Django 5.2.12 on 2026-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_remedy_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete')], default='draft', max_length=10)),
                ('preliminary', models.JSONField(blank=True, default=dict)),
                ('chief_complaints', models.JSONField(blank=True, default=list)),
                ('associated_complaints', models.JSONField(blank=True, default=list)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('generals', models.JSONField(blank=True, default=dict)),
                ('clinical', models.JSONField(blank=True, default=dict)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('prescription', models.JSONField(blank=True, default=dict)),
                ('followup', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Case Paper',
                'verbose_name_plural': 'Case Papers',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='app_casepap_updated_55ac9f_idx'), models.Index(fields=['case_id'], name='app_casepap_case_id_d72ffa_idx')],
            },
        ),
    ]
