# Generated by Django 5.2.12 on 2026-03-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_casepaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePaperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case Paper User',
                'verbose_name_plural': 'Case Paper Users',
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='casepaper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_papers', to='app.casepaperuser'),
        ),
        migrations.AddIndex(
            model_name='casepaper',
            index=models.Index(fields=['user', '-updated_at'], name='app_casepap_user_id_9c8d3c_idx'),
        ),
    ]
