# Generated by Django 5.2.12 on 2026-03-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_casepaperuser_casepaper_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepaperuser',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='physician_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
