# Generated by Django 5.2.12 on 2026-03-24 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_casepaperuser_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google OAuth Token',
                'verbose_name_plural': 'Google OAuth Tokens',
            },
        ),
        migrations.AlterModelOptions(
            name='casepaperuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Case Paper User', 'verbose_name_plural': 'Case Paper Users'},
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email & Password'), ('google', 'Google OAuth')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='clinic_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='True if user completed profile setup'),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='casepaperuser',
            index=models.Index(fields=['email'], name='app_casepap_email_5ac497_idx'),
        ),
        migrations.AddIndex(
            model_name='casepaperuser',
            index=models.Index(fields=['google_id'], name='app_casepap_google__b6495f_idx'),
        ),
        migrations.AddIndex(
            model_name='casepaperuser',
            index=models.Index(fields=['-created_at'], name='app_casepap_created_218305_idx'),
        ),
        migrations.AddField(
            model_name='googleoauthtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_token', to='app.casepaperuser'),
        ),
    ]
