# Generated by Django 5.2.12 on 2026-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepaperuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True if account is active'),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='subscription_type',
            field=models.CharField(blank=True, default='free', max_length=50),
        ),
    ]
