# Generated by Django 5.2.12 on 2026-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_agendaevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaevent',
            options={'ordering': ['date', 'time', '-created_at']},
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
