# Generated by Django 5.2.12 on 2026-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_agendaevent_options_agendaevent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevent',
            name='category',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('followup', 'Follow-up'), ('reminder', 'Reminder'), ('procedure', 'Procedure')], default='reminder', max_length=20),
        ),
    ]
