# Generated by Django 5.2.12 on 2026-04-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_agendaevent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=30, unique=True)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_app_password', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Platform Settings',
                'verbose_name_plural': 'Premium Platform Settings',
            },
        ),
    ]
