# Generated by Django 5.2.12 on 2026-04-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_patientprofile_appointment_quickinvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_desk_enabled', models.BooleanField(default=True)),
                ('doctor_desk_enabled', models.BooleanField(default=True)),
                ('superadmin_tools_visible', models.BooleanField(default=False)),
                ('public_profile_enabled', models.BooleanField(default=False)),
                ('allow_public_booking_requests', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, default='', max_length=120)),
                ('show_phone_public', models.BooleanField(default=False)),
                ('show_email_public', models.BooleanField(default=False)),
                ('whatsapp_notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_settings', to='app.casepaperuser')),
            ],
            options={
                'verbose_name': 'User Workspace Settings',
                'verbose_name_plural': 'User Workspace Settings',
            },
        ),
        migrations.CreateModel(
            name='EPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True, default='')),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('shared_via_email', models.BooleanField(default=False)),
                ('shared_via_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eprescriptions', to='app.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eprescriptions', to='app.patientprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eprescriptions', to='app.casepaperuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_eprescr_user_id_adde5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('reported', 'Reported')], default='ordered', max_length=20)),
                ('report_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requisitions', to='app.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requisitions', to='app.patientprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requisitions', to='app.casepaperuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='app_labrequ_user_id_5054af_idx'), models.Index(fields=['user', '-created_at'], name='app_labrequ_user_id_d3da59_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('concern', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_booking_requests', to='app.casepaperuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='app_publicb_user_id_86e6ef_idx'), models.Index(fields=['user', '-created_at'], name='app_publicb_user_id_186566_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('specialty', models.CharField(blank=True, default='General Practice', max_length=120)),
                ('notes_template', models.TextField(blank=True, default='')),
                ('diagnosis_template', models.TextField(blank=True, default='')),
                ('plan_template', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_templates', to='app.casepaperuser')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'specialty'], name='app_special_user_id_eb3a01_idx'), models.Index(fields=['user', 'is_default'], name='app_special_user_id_a7e03a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VirtualOPDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True)),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('platform', models.CharField(blank=True, default='Google Meet', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('chief_concern', models.CharField(blank=True, default='', max_length=255)),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_sessions', to='app.patientprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_opd_sessions', to='app.casepaperuser')),
            ],
            options={
                'ordering': ['-session_date', '-session_time'],
                'indexes': [models.Index(fields=['user', 'session_date'], name='app_virtual_user_id_dbb8d3_idx'), models.Index(fields=['user', 'status'], name='app_virtual_user_id_7a013b_idx')],
            },
        ),
    ]
