# Generated by Django 5.2.12 on 2026-04-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userworkspacesettings_eprescription_labrequisition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PremiumPlatformSettings',
            new_name='AccessPlatformSettings',
        ),
        migrations.AlterModelOptions(
            name='accessplatformsettings',
            options={'verbose_name': 'Access Platform Settings', 'verbose_name_plural': 'Access Platform Settings'},
        ),
        migrations.AddField(
            model_name='casepaperuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterModelTable(
            name='accessplatformsettings',
            table='app_premiumplatformsettings',
        ),
    ]
