# Generated by Django 5.2.12 on 2026-04-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_add_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkspacesettings',
            name='whatsapp_business_phone_number_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userworkspacesettings',
            name='whatsapp_doctor_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userworkspacesettings',
            name='whatsapp_sender_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
