# Generated by Django 5.2.12 on 2026-04-24 08:19

from django.db import migrations, models
from django.utils.text import slugify


def make_public_slugs_unique(apps, schema_editor):
    UserWorkspaceSettings = apps.get_model('app', 'UserWorkspaceSettings')

    used = set()

    for workspace in UserWorkspaceSettings.objects.select_related('user').all().order_by('id'):
        user = getattr(workspace, 'user', None)
        seed = (
            workspace.public_slug
            or getattr(user, 'clinic_name', '')
            or getattr(user, 'physician_name', '')
            or getattr(user, 'username', '')
            or f'clinic-{workspace.id}'
        )

        base = slugify(seed)[:90].strip('-')
        if not base:
            base = f'clinic-{workspace.id}'

        candidate = base
        counter = 2
        while candidate in used:
            suffix = f'-{counter}'
            candidate = f"{base[:max(1, 120 - len(suffix))]}{suffix}"
            counter += 1

        workspace.public_slug = candidate
        workspace.save(update_fields=['public_slug'])
        used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_userworkspacesettings_whatsapp_business_phone_number_id_and_more'),
    ]

    operations = [
        migrations.RunPython(make_public_slugs_unique, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userworkspacesettings',
            name='public_slug',
            field=models.SlugField(blank=True, default='', max_length=120, unique=True),
        ),
    ]
