# Generated by Django 5.0.6 on 2026-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_userworkspacesettings_public_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedyoftheday',
            name='description',
            field=models.TextField(blank=True, help_text='Short daily insight or keynotes about this remedy.', null=True),
        ),
        migrations.AlterField(
            model_name='remedyoftheday',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedyoftheday',
            name='source',
            field=models.CharField(blank=True, default='boericke', max_length=20, null=True),
        ),
    ]
